version: "3.7"
networks:
  redis:
    driver: bridge
  local:

services:
  redis2:
    image: redis:latest
    container_name: c-redis2
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - redis
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: c-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    network_mode: bridge
