module.exports = [
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Ålandeilanden', code: 'AX' },
  { name: 'Albanië', code: 'AL' },
  { name: 'Algerije', code: 'DZ' },
  { name: 'Amerikaans-Samoa', code: 'AS' },
  { name: 'Andorra', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Anguilla', code: 'AI' },
  { name: 'Antarctica', code: 'AQ' },
  { name: 'Antigua en Barbuda', code: 'AG' },
  { name: 'Argentinië', code: 'AR' },
  { name: 'Armenië', code: 'AM' },
  { name: 'Aruba', code: 'AW' },
  { name: 'Australië', code: 'AU' },
  { name: 'Oostenrijk', code: 'AT' },
  { name: 'Azerbeidzjan', code: 'AZ' },
  { name: "Bahama's", code: 'BS' },
  { name: 'Bahrein', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Wit-Rusland', code: 'BY' },
  { name: 'België', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bermuda', code: 'BM' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Bolivia, Plurinationale Staat', code: 'BO' },
  { name: 'Bonaire, Sint Eustatius en Saba', code: 'BQ' },
  { name: 'Bosnië en Herzegovina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Bouveteiland', code: 'BV' },
  { name: 'Brazilië', code: 'BR' },
  { name: 'Brits Indische Oceaanterritorium', code: 'IO' },
  { name: 'Brunei Darussalam', code: 'BN' },
  { name: 'Bulgarije', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cambodja', code: 'KH' },
  { name: 'Kameroen', code: 'CM' },
  { name: 'Canada', code: 'CA' },
  { name: 'Kaapverdië', code: 'CV' },
  { name: 'Kaaimaneilanden', code: 'KY' },
  { name: 'Centraal-Afrikaanse Republiek', code: 'CF' },
  { name: 'Tsjaad', code: 'TD' },
  { name: 'Chili', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Christmaseiland', code: 'CX' },
  { name: 'Cocoseilanden (Keelingeilanden)', code: 'CC' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Comoren', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Congo, Democratische Republiek', code: 'CD' },
  { name: 'Cookeilanden', code: 'CK' },
  { name: 'Costa Rica', code: 'CR' },
  { name: 'Ivoorkust', code: 'CI' },
  { name: 'Kroatië', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Curaçao', code: 'CW' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Tsjechië', code: 'CZ' },
  { name: 'Denemarken', code: 'DK' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Dominica', code: 'DM' },
  { name: 'Dominicaanse Republiek', code: 'DO' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egypte', code: 'EG' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Equatoriaal-Guinea', code: 'GQ' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Estland', code: 'EE' },
  { name: 'Ethiopië', code: 'ET' },
  { name: 'Falklandeilanden (Malvinas)', code: 'FK' },
  { name: 'Faeröer', code: 'FO' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Finland', code: 'FI' },
  { name: 'Frankrijk', code: 'FR' },
  { name: 'Frans-Guyana', code: 'GF' },
  { name: 'Frans-Polynesië', code: 'PF' },
  { name: 'Franse Zuidelijke Gebieden', code: 'TF' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Georgië', code: 'GE' },
  { name: 'Duitsland', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Gibraltar', code: 'GI' },
  { name: 'Griekenland', code: 'GR' },
  { name: 'Groenland', code: 'GL' },
  { name: 'Grenada', code: 'GD' },
  { name: 'Guadeloupe', code: 'GP' },
  { name: 'Guam', code: 'GU' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guernsey', code: 'GG' },
  { name: 'Guinee', code: 'GN' },
  { name: 'Guinee-Bissau', code: 'GW' },
  { name: 'Guyana', code: 'GY' },
  { name: 'Haïti', code: 'HT' },
  { name: 'Heard en McDonaldeilanden', code: 'HM' },
  { name: 'Heilige Stoel (Vaticaanstad)', code: 'VA' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hongkong', code: 'HK' },
  { name: 'Hongarije', code: 'HU' },
  { name: 'IJsland', code: 'IS' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesië', code: 'ID' },
  { name: 'Iran, Islamitische Republiek', code: 'IR' },
  { name: 'Irak', code: 'IQ' },
  { name: 'Ierland', code: 'IE' },
  { name: 'Man, Eiland', code: 'IM' },
  { name: 'Israël', code: 'IL' },
  { name: 'Italië', code: 'IT' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jersey', code: 'JE' },
  { name: 'Jordanië', code: 'JO' },
  { name: 'Kazachstan', code: 'KZ' },
  { name: 'Kenia', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: 'Korea, Democratische Volksrepubliek', code: 'KP' },
  { name: 'Korea, Republiek', code: 'KR' },
  { name: 'Koeweit', code: 'KW' },
  { name: 'Kirgizië', code: 'KG' },
  { name: 'Laos, Democratische Volksrepubliek', code: 'LA' },
  { name: 'Letland', code: 'LV' },
  { name: 'Libanon', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libië', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Litouwen', code: 'LT' },
  { name: 'Luxemburg', code: 'LU' },
  { name: 'Macau', code: 'MO' },
  { name: 'Macedonië, Voormalige Joegoslavische Republiek', code: 'MK' },
  { name: 'Madagaskar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Maleisië', code: 'MY' },
  { name: 'Maldiven', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Marshalleilanden', code: 'MH' },
  { name: 'Martinique', code: 'MQ' },
  { name: 'Mauritanië', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mayotte', code: 'YT' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Micronesië, Federale Staten van', code: 'FM' },
  { name: 'Moldavië, Republiek', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongolië', code: 'MN' },
  { name: 'Montenegro', code: 'ME' },
  { name: 'Montserrat', code: 'MS' },
  { name: 'Marokko', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibië', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Nederland', code: 'NL' },
  { name: 'Nieuw-Caledonië', code: 'NC' },
  { name: 'Nieuw-Zeeland', code: 'NZ' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Niue', code: 'NU' },
  { name: 'Norfolkeiland', code: 'NF' },
  { name: 'Noordelijke Marianen', code: 'MP' },
  { name: 'Noorwegen', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palau', code: 'PW' },
  { name: 'Palestina, Staat', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papoea-Nieuw-Guinea', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Filipijnen', code: 'PH' },
  { name: 'Pitcairneilanden', code: 'PN' },
  { name: 'Polen', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Puerto Rico', code: 'PR' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Réunion', code: 'RE' },
  { name: 'Roemenië', code: 'RO' },
  { name: 'Russische Federatie', code: 'RU' },
  { name: 'Rwanda', code: 'RW' },
  { name: 'Saint-Barthélemy', code: 'BL' },
  { name: 'Sint-Helena, Ascension en Tristan da Cunha', code: 'SH' },
  { name: 'Saint Kitts en Nevis', code: 'KN' },
  { name: 'Saint Lucia', code: 'LC' },
  { name: 'Saint-Martin (Franse deel)', code: 'MF' },
  { name: 'Saint-Pierre en Miquelon', code: 'PM' },
  { name: 'Saint Vincent en de Grenadines', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'San Marino', code: 'SM' },
  { name: 'Sao Tomé en Principe', code: 'ST' },
  { name: 'Saoedi-Arabië', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Servië', code: 'RS' },
  { name: 'Seychellen', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Sint Maarten (Nederlandse deel)', code: 'SX' },
  { name: 'Slowakije', code: 'SK' },
  { name: 'Slovenië', code: 'SI' },
  { name: 'Salomonseilanden', code: 'SB' },
  { name: 'Somalië', code: 'SO' },
  { name: 'Zuid-Afrika', code: 'ZA' },
  { name: 'Zuid-Georgia en de Zuidelijke Sandwicheilanden', code: 'GS' },
  { name: 'Zuid-Soedan', code: 'SS' },
  { name: 'Spanje', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Soedan', code: 'SD' },
  { name: 'Suriname', code: 'SR' },
  { name: 'Spitsbergen en Jan Mayen', code: 'SJ' },
  { name: 'Swaziland', code: 'SZ' },
  { name: 'Zweden', code: 'SE' },
  { name: 'Zwitserland', code: 'CH' },
  { name: 'Syrische Arabische Republiek', code: 'SY' },
  { name: 'Taiwan', code: 'TW' },
  { name: 'Tadzjikistan', code: 'TJ' },
  { name: 'Tanzania, Verenigde Republiek', code: 'TZ' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Oost-Timor', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tokelau', code: 'TK' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinidad en Tobago', code: 'TT' },
  { name: 'Tunesië', code: 'TN' },
  { name: 'Turkije', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Turks- en Caicoseilanden', code: 'TC' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Oeganda', code: 'UG' },
  { name: 'Oekraïne', code: 'UA' },
  { name: 'Verenigde Arabische Emiraten', code: 'AE' },
  { name: 'Verenigd Koninkrijk', code: 'GB' },
  { name: 'Verenigde Staten', code: 'US' },
  { name: 'Kleine afgelegen eilanden van de Verenigde Staten', code: 'UM' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Oezbekistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Venezuela, Bolivariaanse Republiek', code: 'VE' },
  { name: 'Vietnam', code: 'VN' },
  { name: 'Britse Maagdeneilanden', code: 'VG' },
  { name: 'Amerikaanse Maagdeneilanden', code: 'VI' },
  { name: 'Wallis en Futuna', code: 'WF' },
  { name: 'Westelijke Sahara', code: 'EH' },
  { name: 'Jemen', code: 'YE' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
];
